"""initial schema

Revision ID: 35802f43c044
Revises: 
Create Date: 2026-08-10 22:37:08.662583
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '35802f43c044'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('coach', 'student', name='user_role', native_enum=False, length=32), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=24), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('coach_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('qualifications', sa.Text(), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('specialization', sa.String(length=120), nullable=True),
    sa.Column('primary_location', sa.String(length=120), nullable=True),
    sa.Column('batches', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('drills',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('ball_mastery', 'passing', 'shooting', 'fitness', 'dribbling', name='drill_category', native_enum=False, length=32), nullable=False),
    sa.Column('metric_type', sa.Enum('reps', 'duration_sec', name='metric_type', native_enum=False, length=32), nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Enum('beginner', 'intermediate', 'advanced', name='difficulty', native_enum=False, length=32), nullable=False),
    sa.Column('demo_video_url', sa.String(length=512), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drills_slug'), ['slug'], unique=True)

    op.create_table('student_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('coach_id', sa.Uuid(), nullable=True),
    sa.Column('roster_status', sa.Enum('active', 'removed', name='roster_status', native_enum=False, length=32), nullable=False),
    sa.Column('batch_name', sa.String(length=120), nullable=True),
    sa.Column('course', sa.String(length=120), nullable=True),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('preferred_position', sa.String(length=60), nullable=True),
    sa.Column('dominant_foot', sa.Enum('left', 'right', 'both', name='dominant_foot', native_enum=False, length=32), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('years_playing', sa.Integer(), nullable=True),
    sa.Column('previous_club', sa.String(length=120), nullable=True),
    sa.Column('school_name', sa.String(length=160), nullable=True),
    sa.Column('guardian_name', sa.String(length=120), nullable=True),
    sa.Column('guardian_phone', sa.String(length=24), nullable=True),
    sa.Column('guardian_email', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact', sa.String(length=160), nullable=True),
    sa.Column('medical_notes', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('joined_at', sa.Date(), nullable=True),
    sa.Column('consent_media', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_profiles_batch_name'), ['batch_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_profiles_coach_id'), ['coach_id'], unique=False)

    op.create_table('student_streaks',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('current_weeks', sa.Integer(), nullable=False),
    sa.Column('longest_weeks', sa.Integer(), nullable=False),
    sa.Column('last_met_week', sa.Date(), nullable=True),
    sa.Column('provisional', sa.Boolean(), nullable=False),
    sa.Column('total_approved', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('week_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('approved_count', sa.Integer(), nullable=False),
    sa.Column('pending_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('required_count', sa.Integer(), nullable=False),
    sa.Column('met', sa.Boolean(), nullable=False),
    sa.Column('finalised', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'week_start', name='uq_week_result')
    )
    with op.batch_alter_table('week_results', schema=None) as batch_op:
        batch_op.create_index('ix_week_result_week', ['week_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_week_results_student_id'), ['student_id'], unique=False)

    op.create_table('weekly_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('coach_id', sa.Uuid(), nullable=False),
    sa.Column('batch_name', sa.String(length=120), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coach_id', 'batch_name', 'week_start', name='uq_assignment_batch_week')
    )
    with op.batch_alter_table('weekly_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_assignments_coach_id'), ['coach_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_assignments_week_start'), ['week_start'], unique=False)

    op.create_table('assignment_drills',
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('drill_id', sa.Uuid(), nullable=False),
    sa.Column('required_count', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['weekly_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['drill_id'], ['drills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id', 'drill_id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('coach_id', sa.Uuid(), nullable=True),
    sa.Column('drill_id', sa.Uuid(), nullable=True),
    sa.Column('assignment_id', sa.Uuid(), nullable=True),
    sa.Column('video_key', sa.String(length=512), nullable=False),
    sa.Column('thumbnail_key', sa.String(length=512), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('source', sa.Enum('camera', 'gallery', 'web', name='submission_source', native_enum=False, length=32), nullable=False),
    sa.Column('reps_claimed', sa.Integer(), nullable=True),
    sa.Column('student_note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='submission_status', native_enum=False, length=32), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_approved', sa.Boolean(), nullable=False),
    sa.Column('coach_rating', sa.SmallInteger(), nullable=True),
    sa.Column('coach_feedback', sa.Text(), nullable=True),
    sa.Column('counts_for_week', sa.Date(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('coach_rating IS NULL OR (coach_rating >= 1 AND coach_rating <= 5)', name='ck_submission_rating_range'),
    sa.ForeignKeyConstraint(['assignment_id'], ['weekly_assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['drill_id'], ['drills.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index('ix_submission_coach_status', ['coach_id', 'status'], unique=False)
        batch_op.create_index('ix_submission_status_time', ['status', 'submitted_at'], unique=False)
        batch_op.create_index('ix_submission_student_week', ['student_id', 'counts_for_week'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_coach_id'), ['coach_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_content_hash'), ['content_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_submissions_counts_for_week'), ['counts_for_week'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_student_id'), ['student_id'], unique=False)

    op.create_table('points_ledger',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Enum('approved_submission', 'weekly_goal_met', 'extra_submission', 'high_rating', 'streak_milestone', 'reversal', name='points_reason', native_enum=False, length=32), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('detail', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('points_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_points_ledger_student_id'), ['student_id'], unique=False)
        batch_op.create_index('ix_points_student_week', ['student_id', 'week_start'], unique=False)
        batch_op.create_index('ix_points_week', ['week_start'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('points_ledger', schema=None) as batch_op:
        batch_op.drop_index('ix_points_week')
        batch_op.drop_index('ix_points_student_week')
        batch_op.drop_index(batch_op.f('ix_points_ledger_student_id'))

    op.drop_table('points_ledger')
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissions_student_id'))
        batch_op.drop_index(batch_op.f('ix_submissions_status'))
        batch_op.drop_index(batch_op.f('ix_submissions_counts_for_week'))
        batch_op.drop_index(batch_op.f('ix_submissions_content_hash'))
        batch_op.drop_index(batch_op.f('ix_submissions_coach_id'))
        batch_op.drop_index('ix_submission_student_week')
        batch_op.drop_index('ix_submission_status_time')
        batch_op.drop_index('ix_submission_coach_status')

    op.drop_table('submissions')
    op.drop_table('assignment_drills')
    with op.batch_alter_table('weekly_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_assignments_week_start'))
        batch_op.drop_index(batch_op.f('ix_weekly_assignments_coach_id'))

    op.drop_table('weekly_assignments')
    with op.batch_alter_table('week_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_week_results_student_id'))
        batch_op.drop_index('ix_week_result_week')

    op.drop_table('week_results')
    op.drop_table('student_streaks')
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_profiles_coach_id'))
        batch_op.drop_index(batch_op.f('ix_student_profiles_batch_name'))

    op.drop_table('student_profiles')
    with op.batch_alter_table('drills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drills_slug'))

    op.drop_table('drills')
    op.drop_table('coach_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
